using EFISupportApp.Models.BankStatement;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UglyToad.PdfPig;
using UglyToad.PdfPig.Content;

namespace EFISupportApp
{
    public class ReadPayBillBankStatement
    {
        // --- Regex patterns tuned to the "SEVAARTH" DDO Bank Statement layout ---

        private static readonly Regex MonthYearRegex =
            new(@"Month\s*:\s*(\w+)\s+(\d{4})", RegexOptions.Compiled);

        private static readonly Regex OfficeLineRegex =
            new(@"Name of the Office\s*:\s*(.+?)\s+Treasury\s*:\s*(\S+)\s+DDO\s*:\s*(\S+)",
                RegexOptions.Compiled);

        private static readonly Regex ReportGeneratedRegex =
            new(@"Bank Report\s+(\d{2}-\d{2}-\d{4})\s+(\d{2}:\d{2}:\d{2})", RegexOptions.Compiled);

        private static readonly Regex PayOrderAmountRegex =
            new(@"Total Amount By Pay Order\('\)\s*:\s*([\d,]+)", RegexOptions.Compiled);

        private static readonly Regex CreditedAmountRegex =
            new(@"Total Amount To Be Credited[\s\S]*?:\s*([\d,]+)[\s\S]*?In Employee Account",
                RegexOptions.Compiled);

        private static readonly Regex ChequeAmountRegex =
            new(@"Cheque Amount\('\)\s*:\s*([\d,]+)", RegexOptions.Compiled);

        private static readonly Regex VoucherNoRegex =
            new(@"Treasury Voucher No\.\s*:\s*(\d+)", RegexOptions.Compiled);

        private static readonly Regex VoucherDateRegex =
            new(@"Treasury Voucher Date\s*:\s*(\d{2}/\d{2}/\d{4})", RegexOptions.Compiled);

        // Sr.No  AccountNumber  EmployeeName  NetAmount  [PaymentType]  IFSCCode
        private static readonly Regex EmployeeRowRegex = new(
            @"^\s*(?<sr>\d+)\s+(?<acct>\d{6,})\s+(?<name>.+?)\s+(?<amt>[\d,]+)\s*(?<ptype>[A-Za-z]+)?\s*(?<ifsc>[A-Z]{4}0[A-Z0-9]{6})\s*$",
            RegexOptions.Compiled);

        /// <summary>
        /// Parses every .pdf in the given folder and returns one ParsedStatement per file.
        /// </summary>
        public static List<ParsedStatement> ParseFolder(string folderPath)
        {
            var results = new List<ParsedStatement>();

            foreach (var file in Directory.GetFiles(folderPath, "*.pdf").OrderBy(f => f))
            {
                var text = ExtractText(file);
                var parsed = ParseText(text, Path.GetFileName(file));
                results.Add(parsed);
            }

            return results;
        }

        public static ParsedStatement ExtractFromPdf(string pdfPath)
        {
            var text = ExtractText(pdfPath);
            return ParseText(text, Path.GetFileName(pdfPath));
        }

        /// <summary>
        /// Debug helper: returns the reconstructed line-by-line text for a PDF without
        /// parsing it. Print/inspect this if Master fields or Employees still come out
        /// empty, to see exactly what the regexes are matching against.
        /// </summary>
        public static string GetRawReconstructedText(string pdfPath) => ExtractText(pdfPath);

        private static string ExtractText(string pdfPath)
        {
            using var document = PdfDocument.Open(pdfPath);
            var sb = new System.Text.StringBuilder();
            foreach (var page in document.GetPages())
            {
                sb.AppendLine(ReconstructLines(page));
            }
            return sb.ToString();
        }

        /// <summary>
        /// PdfPig's built-in page.Text sometimes fails to insert line breaks for reports
        /// generated by certain tools (each "line" of the report ends up glued to the next
        /// with no space/newline between them). To be robust against that, we rebuild lines
        /// ourselves from each word's Y position instead of trusting page.Text.
        /// Words whose vertical position (bottom of bounding box) is within a small
        /// tolerance are treated as being on the same visual row, then ordered left-to-right.
        /// </summary>
        private static string ReconstructLines(Page page)
        {
            const double yTolerance = 3.0; // points; tune up slightly if rows still merge/split

            var words = page.GetWords().ToList();
            if (words.Count == 0) return string.Empty;

            var rows = new List<List<Word>>();

            foreach (var word in words.OrderByDescending(w => w.BoundingBox.Bottom))
            {
                var row = rows.FirstOrDefault(r =>
                    Math.Abs(r[0].BoundingBox.Bottom - word.BoundingBox.Bottom) <= yTolerance);

                if (row != null)
                    row.Add(word);
                else
                    rows.Add(new List<Word> { word });
            }

            // Rows were found in descending-Y order already (top of page first);
            // sort each row's words left-to-right for correct reading order.
            var lines = rows.Select(r =>
                string.Join(" ", r.OrderBy(w => w.BoundingBox.Left).Select(w => w.Text)));

            return string.Join("\n", lines);
        }

        private static ParsedStatement ParseText(string text, string sourceFileName)
        {
            var master = new MasterRecord { SourceFile = sourceFileName };

            var monthYear = MonthYearRegex.Match(text);
            if (monthYear.Success)
            {
                master.Month = monthYear.Groups[1].Value;
                master.Year = int.Parse(monthYear.Groups[2].Value);
            }

            var officeLine = OfficeLineRegex.Match(text);
            if (officeLine.Success)
            {
                master.OfficeName = officeLine.Groups[1].Value.Trim();
                master.Treasury = officeLine.Groups[2].Value.Trim();
                master.DdoCode = officeLine.Groups[3].Value.Trim();
            }

            var reportGen = ReportGeneratedRegex.Match(text);
            if (reportGen.Success)
            {
                master.ReportGeneratedDate = ParseDateTimeSafe(
                    reportGen.Groups[1].Value, reportGen.Groups[2].Value);
            }

            master.TotalAmountByPayOrder = ParseAmount(PayOrderAmountRegex, text);
            master.TotalAmountCreditedToEmployeeAccount = ParseAmount(CreditedAmountRegex, text);
            master.ChequeAmount = ParseAmount(ChequeAmountRegex, text);

            var voucherNo = VoucherNoRegex.Match(text);
            if (voucherNo.Success) master.VoucherNo = voucherNo.Groups[1].Value.Trim();

            var voucherDate = VoucherDateRegex.Match(text);
            if (voucherDate.Success)
                master.VoucherDate = DateTime.ParseExact(
                    voucherDate.Groups[1].Value, "dd/MM/yyyy", CultureInfo.InvariantCulture);

            // --- Employee rows ---
            var employees = new List<EmpBankDetail>();
            foreach (var rawLine in text.Split('\n'))
            {
                var line = rawLine.Trim();
                var m = EmployeeRowRegex.Match(line);
                if (!m.Success) continue;

                employees.Add(new EmpBankDetail
                {
                    SrNo = int.Parse(m.Groups["sr"].Value),
                    AccountNumber = m.Groups["acct"].Value,
                    EmployeeName = Regex.Replace(m.Groups["name"].Value, @"\s+", " ").Trim(),
                    NetAmount = decimal.Parse(m.Groups["amt"].Value, NumberStyles.AllowThousands,
                        CultureInfo.InvariantCulture),
                    PaymentType = m.Groups["ptype"].Success ? m.Groups["ptype"].Value.Trim() : "",
                    IfscCode = m.Groups["ifsc"].Value.Trim()
                });
            }

            return new ParsedStatement { Master = master, Employees = employees };
        }

        private static decimal ParseAmount(Regex regex, string text)
        {
            var match = regex.Match(text);
            if (!match.Success) return 0m;
            return decimal.Parse(match.Groups[1].Value, NumberStyles.AllowThousands,
                CultureInfo.InvariantCulture);
        }

        private static DateTime? ParseDateTimeSafe(string datePart, string timePart)
        {
            var combined = $"{datePart} {timePart}";
            if (DateTime.TryParseExact(combined, "dd-MM-yyyy HH:mm:ss",
                CultureInfo.InvariantCulture, DateTimeStyles.None, out var dt))
                return dt;
            return null;
        }

    }
}
